steps:
  - label: ":construction_worker: Build"
    command: echo "Build the rocket"
    key: build
    branches: main
    plugins:
      - docker#v5.13.0:
          image: "ubuntu:latest"

  - label: ":white_check_mark: Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: ":rocket: Deploy"
    command: |
      echo "Launch the rocket" | tee .buildkite/annotation.md
      cat .buildkite/annotation.md | buildkite-agent annotate --style "success"
    key: deploy
    depends_on: test
    agents:
      driver: 580
