steps:
  - label: ":construction_worker: Build"
    command: |
      echo "Build the rocket"
      buildkite-agent oidc request-token --audience sts.amazonaws.com > token
      cat token
      echo "linebr"
      buildkite-agent redactor add token
      echo "something"
      cat token
      echo "else"
    key: build
    branches: main

  - label: ":white_check_mark: Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: ":rocket: Deploy"
    command: |
      echo "Launch the $USR_ARCH rocket" | tee .buildkite/annotation.md
      cat .buildkite/annotation.md | buildkite-agent annotate --style "success"
    key: deploy
    depends_on: test
    agents:
      driver: 580
    matrix:
      setup:
        arch:
          - amd64
          - arm64
    env:
      USR_ARCH: "{{ matrix.arch }}"

  - label: ":rocket: Dynamic"
    command: |
      ./dynamic.sh 1 | tee /dev/stderr | buildkite-agent pipeline upload
      ./dynamic.sh 2 | tee /dev/stderr | buildkite-agent pipeline upload
    key: dynamic
