steps:
  - label: ":construction_worker: Build"
    command: |
      mkdir -p .buildkite
      echo "Build the rocket" | tee .buildkite/annotation.md
    key: build

  - label: ":white_check_mark: Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: ":rocket: Deploy"
    command: |
      echo "Launch the rocket"
      ls -al . ./.buildkite
      cat .buildkite/annotation.md | buildkite-agent annotate --style "success"
    key: deploy
    depends_on: test
