steps:
  - label: ":construction_worker: Build"
    command: |
      echo "Build the rocket"
      buildkite-agent oidc request-token --audience sts.amazonaws.com > token
      cat token
      echo "linebr"
      buildkite-agent redactor add token
      echo "something"
      cat token
      echo "else"
    key: build
    branches: main

  - label: ":white_check_mark: Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: ":rocket: Deploy"
    command: |
      echo "Launch the rocket" | tee .buildkite/annotation.md
      cat .buildkite/annotation.md | buildkite-agent annotate --style "success"
    key: deploy
    depends_on: test
    agents:
      driver: 580

  - label: ":rocket: Dynamic"
    command: |
      bash dynamic.sh | buildkite-agent pipeline upload
    key: dynamic
