steps:
  - label: ":rocket: Example Matrix"
    command: |
      echo "Launch the \$USR_ARCH rocket" | tee .buildkite/annotation.md
      cat .buildkite/annotation.md | buildkite-agent annotate --append --style "success"
    key: matrix
    agents:
      driver: 580
    matrix:
      setup:
        arch:
          - amd64
          - arm64
    env:
      USR_ARCH: "{{ matrix.arch }}"

  - label: ":rocket: Build"
    command: |
      ./generate-builds.sh 1 | tee /dev/stderr | buildkite-agent pipeline upload
    key: build

  - label: ":white_check_mark: Test"
    command: |
      ./generate-tests.sh 1 | tee /dev/stderr | buildkite-agent pipeline upload
    depends_on: build
